

INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (1, 'Strosin', 55, 'Saint Lucia', 'Peru');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (2, 'Harvey', 70, 'Greenland', 'DarkSalmon');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (3, 'Larson', 94, 'Sao Tome and Principe', 'Green');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (4, 'Ritchie', 30, 'Belize', 'Orchid');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (5, 'Zemlak', 45, 'French Guiana', 'Red');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (6, 'Larkin', 27, 'Bermuda', 'ForestGreen');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (7, 'Brekke', 99, 'Nauru', 'Linen');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (8, 'Mosciski', 77, 'Belize', 'Black');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (9, 'Pouros', 10, 'Cook Islands', 'IndianRed ');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (10, 'Barrows', 64, 'Saint Martin', 'Cyan');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (11, 'Lockman', 94, 'Yemen', 'GreenYellow');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (12, 'Barrows', 30, 'Serbia', 'Gold');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (13, 'Wunsch', 28, 'Afghanistan', 'DarkBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (14, 'Kuphal', 74, 'Benin', 'OldLace');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (15, 'Raynor', 43, 'Cameroon', 'Thistle');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (16, 'Ebert', 15, 'Martinique', 'MediumTurquoise');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (17, 'Breitenberg', 13, 'Jersey', 'Navy');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (18, 'Williamson', 20, 'Kiribati', 'Darkorange');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (19, 'Bartell', 50, 'Solomon Islands', 'Linen');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (20, 'Eichmann', 13, 'Maldives', 'Indigo ');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (21, 'Kohler', 76, 'Peru', 'WhiteSmoke');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (22, 'Mertz', 56, 'Micronesia', 'SteelBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (23, 'Bechtelar', 57, 'Uzbekistan', 'Green');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (24, 'Mills', 19, 'Bolivia', 'DarkRed');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (25, 'Jast', 82, 'Brazil', 'LightPink');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (26, 'Hudson', 92, 'Comoros', 'MediumVioletRed');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (27, 'Schiller', 55, 'Comoros', 'Darkorange');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (28, 'Walter', 72, 'Indonesia', 'Lavender');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (29, 'Barton', 91, 'Iceland', 'Green');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (30, 'Orn', 18, 'Isle of Man', 'Maroon');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (31, 'Hills', 52, 'British Indian Ocean Territory (Chagos Archipelago)', 'FloralWhite');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (32, 'McKenzie', 65, 'Chad', 'Snow');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (33, 'Howe', 26, 'Bermuda', 'MistyRose');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (34, 'Macejkovic', 18, 'Eritrea', 'DarkGoldenRod');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (35, 'Gulgowski', 82, 'San Marino', 'DarkBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (36, 'Farrell', 34, 'Gabon', 'PaleGoldenRod');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (37, 'Konopelski', 84, 'Netherlands Antilles', 'MidnightBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (38, 'Conroy', 20, 'Nicaragua', 'GoldenRod');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (39, 'Keebler', 98, 'Peru', 'AliceBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (40, 'Prohaska', 64, 'Bangladesh', 'DimGrey');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (41, 'Smith', 96, 'Ethiopia', 'ForestGreen');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (42, 'Bayer', 33, 'Lao People\'s Democratic Republic', 'Orchid');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (43, 'Miller', 77, 'Jamaica', 'Black');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (44, 'Toy', 45, 'Latvia', 'LightGoldenRodYellow');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (45, 'Lang', 42, 'Suriname', 'MistyRose');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (46, 'Strosin', 97, 'Bolivia', 'DarkMagenta');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (47, 'Lang', 29, 'Korea', 'Black');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (48, 'Legros', 24, 'Thailand', 'Maroon');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (49, 'Boehm', 18, 'Tokelau', 'PowderBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (50, 'Osinski', 47, 'Spain', 'DarkRed');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (51, 'Rippin', 78, 'Fiji', 'DarkKhaki');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (52, 'Lowe', 54, 'Liechtenstein', 'GoldenRod');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (53, 'Bergstrom', 23, 'Andorra', 'MediumTurquoise');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (54, 'Nikolaus', 83, 'Trinidad and Tobago', 'Cyan');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (55, 'Barton', 17, 'Isle of Man', 'Turquoise');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (56, 'Bailey', 29, 'Sweden', 'DarkMagenta');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (57, 'Larkin', 73, 'Tajikistan', 'LightSkyBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (58, 'Schultz', 49, 'Benin', 'Plum');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (59, 'Skiles', 73, 'Poland', 'OldLace');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (60, 'Runte', 10, 'Serbia', 'Pink');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (61, 'McClure', 22, 'Trinidad and Tobago', 'SlateGray');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (62, 'Ruecker', 68, 'Vanuatu', 'Magenta');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (63, 'Dach', 14, 'Serbia', 'LightSeaGreen');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (64, 'Botsford', 39, 'Guatemala', 'PaleVioletRed');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (65, 'Yundt', 76, 'Grenada', 'DeepPink');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (66, 'Howe', 72, 'Sierra Leone', 'DarkKhaki');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (67, 'Will', 48, 'Mexico', 'DeepSkyBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (68, 'Haley', 24, 'Chad', 'LightCyan');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (69, 'O\'Conner', 36, 'Aruba', 'Teal');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (70, 'Hand', 62, 'Palestinian Territory', 'Ivory');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (71, 'Haley', 50, 'Jersey', 'GoldenRod');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (72, 'Gottlieb', 44, 'Qatar', 'MediumOrchid');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (73, 'Kertzmann', 29, 'Togo', 'YellowGreen');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (74, 'Price', 78, 'Belize', 'Gray');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (75, 'Rice', 78, 'French Polynesia', 'FloralWhite');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (76, 'Hettinger', 13, 'Northern Mariana Islands', 'Orchid');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (77, 'Schmidt', 24, 'Cambodia', 'Gold');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (78, 'Koss', 91, 'Mongolia', 'SpringGreen');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (79, 'Keeling', 92, 'Kenya', 'Fuchsia');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (80, 'Kerluke', 83, 'French Southern Territories', 'Bisque');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (81, 'Hills', 60, 'Bouvet Island (Bouvetoya)', 'MediumBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (82, 'Gleason', 19, 'Bosnia and Herzegovina', 'AntiqueWhite');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (83, 'Schamberger', 59, 'Cambodia', 'DarkSlateBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (84, 'Dickinson', 35, 'Ecuador', 'SeaShell');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (85, 'Dare', 74, 'Latvia', 'LawnGreen');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (86, 'Aufderhar', 53, 'Bulgaria', 'Magenta');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (87, 'Schmidt', 71, 'Australia', 'DarkBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (88, 'Kub', 73, 'Saint Barthelemy', 'DarkKhaki');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (89, 'Hoeger', 54, 'Western Sahara', 'PeachPuff');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (90, 'Ruecker', 82, 'Germany', 'Lavender');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (91, 'Zemlak', 100, 'Belgium', 'Aquamarine');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (92, 'McGlynn', 78, 'Korea', 'OldLace');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (93, 'Yundt', 26, 'Belarus', 'LightSteelBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (94, 'Eichmann', 56, 'Togo', 'Blue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (95, 'Rohan', 35, 'Comoros', 'DeepSkyBlue');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (96, 'Bosco', 58, 'Kyrgyz Republic', 'Lime');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (97, 'Stoltenberg', 78, 'Burundi', 'Snow');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (98, 'Bins', 87, 'Vanuatu', 'OliveDrab');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (99, 'Gaylord', 39, 'Heard Island and McDonald Islands', 'WhiteSmoke');
INSERT INTO `person` (`id`, `name`, `age`, `country`, `favourit_colour`) VALUES (100, 'Wuckert', 11, 'Micronesia', 'Red');person